"""Public dependency-free contracts shared by PapaGUI client and server."""

from ._base import ContractValidationError, JsonDto, JsonValue
from .customers import (
    Contact,
    Customer,
    CustomerJournalEntry,
    CustomerMutationEnvelope,
    CustomerProject,
    IdempotencyKey,
    JournalEntry,
    MutationEnvelope,
    MutationOperation,
    MutationTarget,
)
from .catalog import CatalogFacets, CatalogFile, CatalogFolder, CatalogProjectRoot
from .errors import (
    ApiError,
    ApiErrorPayload,
    ConflictErrorPayload,
    ConflictPayload,
    ErrorDetail,
)
from .generations import (
    GENERATION_SCHEMA_VERSION,
    GenerationComponentKind,
    GenerationComponent,
    GenerationComponentManifest,
    GenerationManifest,
    SourcePath,
)
from .settings import (
    MAX_INDEX_INTERVAL_SECONDS,
    MIN_INDEX_INTERVAL_SECONDS,
    IndexSettings,
    ResourceProfile,
)
from .recognition import (
    CustomerSuggestion,
    CustomerSuggestionDecision,
    CustomerSuggestionStatus,
    Decision,
    Evidence,
    RecognitionCase,
    RecognitionCaseStatus,
    RecognitionDecision,
    RecognitionDecisionAction,
    RecognitionEvidence,
    RecognitionRunSummary,
    RunSummary,
)
from .status import (
    ACTIVE_INDEX_STATES,
    DocumentWorkerStatus,
    IndexProgress,
    IndexRunState,
    IndexRunStatus,
    IndexStatus,
    ServerState,
    ServerStatus,
)
from .system import (
    CONTRACT_VERSION,
    Capability,
    Capabilities,
    SystemInfo,
    SystemCapabilities,
)


__version__ = CONTRACT_VERSION

__all__ = [
    "ACTIVE_INDEX_STATES",
    "CONTRACT_VERSION",
    "GENERATION_SCHEMA_VERSION",
    "MAX_INDEX_INTERVAL_SECONDS",
    "MIN_INDEX_INTERVAL_SECONDS",
    "ApiError",
    "ApiErrorPayload",
    "Capabilities",
    "CatalogFacets",
    "CatalogFile",
    "CatalogFolder",
    "CatalogProjectRoot",
    "Capability",
    "ConflictErrorPayload",
    "ConflictPayload",
    "Contact",
    "ContractValidationError",
    "Customer",
    "CustomerJournalEntry",
    "CustomerMutationEnvelope",
    "CustomerProject",
    "CustomerSuggestion",
    "CustomerSuggestionDecision",
    "CustomerSuggestionStatus",
    "Decision",
    "ErrorDetail",
    "Evidence",
    "GenerationComponentKind",
    "GenerationComponent",
    "GenerationComponentManifest",
    "GenerationManifest",
    "IdempotencyKey",
    "IndexProgress",
    "IndexRunState",
    "IndexRunStatus",
    "IndexSettings",
    "IndexStatus",
    "JournalEntry",
    "JsonDto",
    "JsonValue",
    "MutationEnvelope",
    "MutationOperation",
    "MutationTarget",
    "ResourceProfile",
    "RecognitionCase",
    "RecognitionCaseStatus",
    "RecognitionDecision",
    "RecognitionDecisionAction",
    "RecognitionEvidence",
    "RecognitionRunSummary",
    "RunSummary",
    "ServerState",
    "ServerStatus",
    "DocumentWorkerStatus",
    "SourcePath",
    "SystemInfo",
    "SystemCapabilities",
    "__version__",
]
