"""Ports owned by the application services which consume them."""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any, Protocol

from papagui_server.domain.models import CustomerMutationResult, ServerSettings


class CustomerRepositoryPort(Protocol):
    def list(self, *, limit: int = 500, offset: int = 0) -> list[dict[str, Any]]: ...
    def get(self, customer_id: int) -> dict[str, Any] | None: ...
    def create(self, customer: dict[str, Any]) -> dict[str, Any]: ...
    def update(
        self, customer_id: int, customer: dict[str, Any], expected_revision: int
    ) -> dict[str, Any]: ...
    def delete(self, customer_id: int, expected_revision: int) -> None: ...
    def add_journal(
        self, customer_id: int, entry: dict[str, Any], expected_revision: int
    ) -> tuple[dict[str, Any], int]: ...
    def update_journal(
        self,
        customer_id: int,
        entry_id: int,
        entry: dict[str, Any],
        expected_revision: int,
    ) -> tuple[dict[str, Any], int]: ...
    def delete_journal(
        self, customer_id: int, entry_id: int, expected_revision: int
    ) -> int: ...
    def idempotency_result(
        self, key: str, request_hash: str
    ) -> CustomerMutationResult | None: ...
    def remember_idempotency(
        self,
        key: str,
        request_hash: str,
        operation: str,
        result: CustomerMutationResult,
    ) -> None: ...
    def add_document_suggestion(
        self,
        customer_id: int,
        *,
        kind: str,
        value: str,
        source_path: str,
        excerpt: str,
        fingerprint: str,
        confidence: float,
    ) -> bool: ...


class CustomerUnitOfWorkPort(Protocol):
    customers: CustomerRepositoryPort
    projects: Any
    suggestions: Any
    recognition: Any
    def __enter__(self) -> "CustomerUnitOfWorkPort": ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
    def commit(self) -> None: ...


class CustomerUnitOfWorkFactory(Protocol):
    def __call__(self) -> CustomerUnitOfWorkPort: ...


class SettingsRepositoryPort(Protocol):
    def load(self) -> ServerSettings: ...
    def save(self, settings: ServerSettings) -> None: ...


class RunStateRepositoryPort(Protocol):
    def load(self) -> dict[str, Any] | None: ...
    def save(self, payload: dict[str, Any]) -> None: ...


class SourceIdentityGuardPort(Protocol):
    def probe(self, source_path: Path, source_id: str) -> tuple[bool, str]: ...
    def ensure_ready(self, source_path: Path, source_id: str) -> None: ...


class CatalogIndexerPort(Protocol):
    def build(
        self,
        source_path: Path,
        *,
        source_id: str,
        full_rebuild: bool,
        settings: ServerSettings,
        cancelled: Callable[[], bool],
        progress: Callable[[int, str], None],
    ) -> Path: ...
    def delete(self) -> None: ...


class CatalogReaderPort(Protocol):
    def search(self, **query: Any) -> dict[str, Any]: ...
    def facets(self, *, source_id: str) -> dict[str, Any]: ...
    def list_folders(self, **query: Any) -> list[dict[str, Any]]: ...
    def folder_details(self, *, source_id: str, relative_path: str) -> dict[str, Any]: ...
    def list_project_roots(self, *, source_id: str) -> list[dict[str, Any]]: ...
    def project_root(self, *, source_id: str, project_root_id: int) -> dict[str, Any]: ...
    def document_evidence(self, **query: Any) -> list[dict[str, Any]]: ...


class CustomerRecognizerPort(Protocol):
    def synchronize(
        self, source_path: Path, *, source_id: str, minimum_year: int
    ) -> dict[str, int]: ...


class GenerationPublisherPort(Protocol):
    def publish_index(self) -> dict[str, Any]: ...
    def publish_customers(self) -> dict[str, Any]: ...
    def publish_all(self) -> dict[str, Any]: ...
    def current(self) -> dict[str, Any] | None: ...
    def retention_status(self) -> dict[str, Any]: ...
    def delete_index_generations(self) -> None: ...
